Fixing #852 - Removing duplicate icons on the map viewer and defaulti…
CellularPrivacy/Android-IMSI-Catcher-Detector pull request #906
Opened 2016-10-27 23:47 UTC by rm-star

>Thank you for submitting a pull request! Please add below details so that we can merge it faster.

---

#### Agreements
>Please check these boxes to ensure you've actually read and understood these important rules!

- [* ] **I have reviewed and accepted the [guidelines for contributing](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md) to this project.**
- [ *] **I have reviewed and closely followed the [Style Guide](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/wiki/Style-Guide) for this Android app.**

---

#### Overview
Adding a fix for issue 852.
Removing duplicate user icons on the map by clearing out previous layers on a refresh and only creating new layers if a previous one does not already exist.
Defaulting the map view to move to the users current position instead of an indeterminate one.
---

#### Classification
>Please click the correct checkbox that applies best to classify your pull request.

- [ *] Bugfix (non-breaking change which fixes an existing issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor (restructuring of existing code without changing its external functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

---

#### References
>If your pull request is related to or solves any existing Issues, please link them here.
#852 
---

#### Screenshots
>If you have created visual changes, please add a screenshot without metadata here.
N/A
…ng to view the users current position instead of an indeterminate position

2016-11-30 18:47 UTC, mimi89999 commented on AIMSICD/src/main/java/com/secupwn/aimsicd/ui/fragments/MapFragment.java
> +        if (null == mCompassOverlay) {
Could you keep the `null` and other values on the right of logical operators to keep the code consistent?

2016-12-05 22:49 UTC, rm-star commented on AIMSICD/src/main/java/com/secupwn/aimsicd/ui/fragments/MapFragment.java
> +        if (null == mCompassOverlay) {
Certainly, it's done now.

2016-12-06 13:32 UTC, mimi89999 commented
In MapViewerOsmDroid.java also...

Le 5 décembre 2016 23:49:17 GMT+01:00, rm-star <notifications@github.com> a écrit :
>rm-star commented on this pull request.
>
>
>
>>          // Check if we were successful in obtaining the map.
>         mMap.setBuiltInZoomControls(true);
>         mMap.setMultiTouchControls(true);
>         mMap.setMinZoomLevel(3);
>         mMap.setMaxZoomLevel(19); // Latest OSM can go to 21!
>         mMap.getTileProvider().createTileCache();
>-        mCompassOverlay = new CompassOverlay(getActivity(), new
>InternalCompassOrientationProvider(getActivity()), mMap);
>+
>+        if (null == mCompassOverlay) {
>
>Certainly, it's done now.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/pull/906

2016-12-06 23:01 UTC, rm-star commented
Good catch, fixed now.

On 6 December 2016 at 13:32, Michel Le Bihan <notifications@github.com>
wrote:

> In MapViewerOsmDroid.java also...
>
> Le 5 décembre 2016 23:49:17 GMT+01:00, rm-star <notifications@github.com>
> a écrit :
> >rm-star commented on this pull request.
> >
> >
> >
> >> // Check if we were successful in obtaining the map.
> > mMap.setBuiltInZoomControls(true);
> > mMap.setMultiTouchControls(true);
> > mMap.setMinZoomLevel(3);
> > mMap.setMaxZoomLevel(19); // Latest OSM can go to 21!
> > mMap.getTileProvider().createTileCache();
> >- mCompassOverlay = new CompassOverlay(getActivity(), new
> >InternalCompassOrientationProvider(getActivity()), mMap);
> >+
> >+ if (null == mCompassOverlay) {
> >
> >Certainly, it's done now.
> >
> >--
> >You are receiving this because you commented.
> >Reply to this email directly or view it on GitHub:
> >https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/pull/906
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/pull/906#issuecomment-265150203>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFL9xr7r2nSPlxZ00idLYzjob39BEgqtks5rFWPzgaJpZM4Ki8Y3>
> .
>

2016-12-06 23:02 UTC, rm-star commented on AIMSICD/src/main/java/com/secupwn/aimsicd/ui/fragments/MapFragment.java
> +        if (null == mCompassOverlay) {
Fixed MapViewerOsmDroid.java as well

2016-12-13 19:17 UTC, mimi89999 commented
@rm-star The code looks OK. Could you squash your 3 commits into 1?

@larsgrefer Could you have a look at this PR?

2016-12-13 19:20 UTC, mimi89999 requested changes
The commits need to be squashed.

2016-12-21 23:29 UTC, rm-star commented
I think it's squashed now

On 13 December 2016 at 19:20, Michel Le Bihan <notifications@github.com>
wrote:

> *@mimi89999* requested changes on this pull request.
>
> The commits need to be squashed.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/pull/906#pullrequestreview-12756823>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFL9xkwKTYsVmbc0qqdstubjex2cxRwIks5rHu_vgaJpZM4Ki8Y3>
> .
>

2017-01-14 20:52 UTC, merged